name: tio
version: '1.36'
summary: A simple TTY terminal I/O tool
description: >
  tio is a simple TTY terminal tool which features a straightforward
  commandline interface to easily connect to TTY devices for basic I/O
  operations.

base: core20
grade: stable
confinement: classic

apps:
  tio:
    command: usr/bin/tio
    completer: usr/share/bash-completion/completions/tio

parts:
  tio:
    plugin: meson
    source: https://github.com/tio/tio.git
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - pkg-config
      - cmake
      - bash-completion
    stage-packages:
      - bash-completion
